### ISSUE TITLE
Any chance of replacing Newtonsoft.Json with System.Text.Json and using .net standard 2.0

### ISSUE THREAD

**Issue by sensslen** [tngraf/Tethys.SPDX#2]
As the title states, this is more of a question than a issue. I took a look at the nuget packages provided by this project lately and would really like to use  [Tethys.SPDX.KnownLicenses](https://www.nuget.org/packages/Tethys.SPDX.KnownLicenses) and [Tethys.SPDX.ExpressionParser](https://www.nuget.org/packages/Tethys.SPDX.ExpressionParser) in https://github.com/sensslen/nuget-license to allow for proper expression parsing. However there are two things tat prevent me from doing so:
1. both nuget packages are using .net standard 2.1 which is not compatible with .net framework. Unfortunately I need to also publish to .net framework in order to properly support native c++ projects (one of the projects I created a PR for downgrading the .net version --> see #1 ).
2. [Tethys.SPDX.KnownLicenses](https://www.nuget.org/packages/Tethys.SPDX.KnownLicenses) uses Newtonsoft.Json with a lot of custom converters. I really want to keep the dependencies to a minimum and since Microsoft includes System.Text.Json with .net, it's a natural fit for json serialization/deserialization.

**Comment by tngraf** [comment]
It should be possible to use System.Text.Json for KnownLicenses. ExpressionParser does not need any serialization.  
SpdxWriter and SimpleSpdxParser make heavy use of NewtonSoft custom serializations - this would be really hard.

**Comment by sensslen** [comment]
I'll work on a PR then....

**Comment by sensslen** [comment]
#4

**Comment by tngraf** [comment]
All done: [Tethys.SPDX.KnownLicenses](https://www.nuget.org/packages/Tethys.SPDX.KnownLicenses) uses `System.Text.Json` and all packages use `netstandard2.0`.

**Comment by sensslen** [comment]
@tngraf thanks for making this work!
